CREATE TABLE CLIENTE (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTO (
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO (
    ID SERIAL PRIMARY KEY,
    CLIENTE_ID INTEGER,
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMERIC(20,2),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE ITEM_PEDIDO (
    ID SERIAL PRIMARY KEY,
    PEDIDO_ID INTEGER,
    PRODUTO_ID INTEGER,
    QUANTIDADE INTEGER,
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);
